config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  patch 'posts/:id' => 'posts#update', as: 'update_post'
  patch 'users/:id' => 'users#update', as: 'update_user'

resources :posts, only: [:new, :create, :index, :show, :edit, :destroy] do
  resource :favorite, only: [:create, :destroy]
end
resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to post_path(post)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
     @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:shop_name, :image, :caption)
  end

#:name, :image, :introduction
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

app/views/homes/top.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="px-3 mx-auto">ようこそ
          グルメ岩手！へ
        </h1>
        <p>
          <strong>グルメ岩手！</strong>
          では,
        </p>
        <p>
          岩手県内のレストランの紹介や美味しいお店を発掘することができます！
        </p>
        <p>
          皆で岩手の美味しいを広めよう！
        </p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <td>
              <%= link_to "ログイン", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sing_in" %>
            </td>
          </div>
          <div class="row">
            <td>
              <%= link_to "新規登録", new_user_registration_path, class: "btn btn-success btn-sm btn-block sing_up" %>
            </td>
        </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IwateGourmet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/ef8e0ab2ed.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo2.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="p-3 mb-2 bg-warning text-dark pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>岩手の美味しいを広めよう！</p>
            <a class="text-dark mt-2 mb-3" href="/">
              <strong>グルメ岩手！</strong>
            </a>
          </div>
          <div class="col-md-8">
            <h6 class="text-dark mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-dark">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-dark">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h1 class="text-dark bg-light p-4 mb-0">編集画面</h1>
        <div class="form-body p-4">

          <%= form_with model: @post, url: update_post_path(@post.id), method: :patch do |f| %>

          　<h4>画像</h4>
          　<%= f.file_field :image, placeholder: "画像", accept: "image/*", class: "w-100"  %>

          　<div class="patch-group mb-3 mt-4">
              <h4>店舗名</h4>
              <%= f.text_field :shop_name, class: "form-control", placeholder: "店舗名" %>

              <h4>コメント</h4>
              <%= f.text_area :caption, class: "form-control", rows: "3", placeholder: "コメント" %>
            </div>

            <%= f.submit '保存', class: "btn btn-lg btn-block btn-info mt-4"  %>

          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="card-list-container py-5">
  <% @posts.each do |post| %>
    <div class="card w-50 mx-auto mt-4 shadow-lg">
      <%= link_to post_path(post.id) do %>
        <%= image_tag post.get_image, class: "card-img-top"; %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= image_tag post.user.get_profile_image(100,100), class: "mt-3 rounded-circle"; %>
          </div>
          <div class="col-10">
            <p class="card-title">
              <%= link_to(post_path(post.id), class: "text-dark") do %>
                <strong><i class="fa-solid fa-shop"></i><span> <%= post.shop_name %></span></strong>
              <% end %>
            </p>
            <p class="card-text">コメント：<%= post.caption %></p>
            <span><i class="fas fa-user"></i> By <%= post.user.name %> ｜ </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post.errors.count %>件のエラーが発生しました
            </h6>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fa-solid fa-shop"></i></span>
            </div>
            <%= f.text_field :shop_name, class: "form-control", placeholder: "店舗名" %>
          </div>
          <%= f.text_area :caption, class: "form-control", rows: "3", placeholder: "コメント" %>
          <hr>
          <%= f.submit '投稿', class: "btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card-list-container py-5">
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= image_tag @post.get_image, class: "card-img-top"; %>
    <div class="card-body">
      <div class="row">

        <div class="col-10">
          <p class="card-title">
            店舗名：<%= @post.shop_name %>
          </p>
          <p class="card-text">
            コメント：<%= @post.caption %>
          </p>
          <p>投稿ユーザー画像：<%= image_tag @post.user.get_profile_image(100,100) %></p>
          <p>ユーザーネーム：<%= @post.user.name %></p>
          <p>投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>
          <%= link_to "編集", edit_post_path(@post.id) %>
          <% if @post.user == current_user %>
            <%= link_to "削除", post_path(@post), method: :delete %>
          <% end %>
          <% if @post.favorited_by?(current_user) %>
            <p>
              <%= link_to post_favorite_path(@post), method: :delete do %>
                ♥<%= @post.favorites.count %> いいね
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to post_favorite_path(@post), method: :post do %>
                ♡<%= @post.favorites.count %> いいね
              <% end %>
            </p>
        </div>
      </div>

  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user, url: update_user_path(@user.id), method: :patch do |f| %>
  <label for="inputName">名前</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">プロフィール画像</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <% if @user == current_user %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user.id) %></p>
  <% end %>
</div>

<% @posts.each do |post| %>
<div>
  <%= link_to post_path(post.id) do %>
    <%= image_tag post.get_image, size: "500x500" %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag post.user.get_profile_image(100,100) %></p>
  <p>店舗名：<%= post.shop_name %></p>
  <p>コメント：<%= post.caption %></p>
  <p>ユーザーネーム：<%= post.user.name %></p>
</div>
<% end %>